### ISSUE TITLE
[PROPOSAL]

### ISSUE THREAD

**Issue by Ecoins3255** [chainstack/developer-hub-content#1]
- Content is:
[ ] Play & Earn
[ ] The article will focus on the rise in P&E, their legitimacy and what the future of that industry looks like. The article will be balanced and will keep the readers engaged and informed to a tee.
[ ] Nfts(Non fungible tokens)- representing data of unique features on the Blockchain 

- A play-to-earn game is one that rewards its participants with digital cash or non-fungible tokens

**Comment by uF4No** [comment]
Hi @Ecoins3255 We've been considering this proposal but it's not something we're interested in at this time
