### ISSUE TITLE
[PROPOSAL] Publishing your first Ethereum smart contract

### ISSUE THREAD

**Issue by tster** [chainstack/developer-hub-content#10]
- Content is:
  [ x ] Coding tutorial
  [ ] Informational content
  [ ] Other (describe)

- Which blockchain protocol is this about?: Ethereum / all EVM

- Description (two or three phrases describing what is it about): This would be a beginner's guide to publishing an Ethereum smart contract, intended for somebody with little-to-no prior technical knowledge. As an example, code would show the publishing of an NFT smart contract.

- Have you published articles in a blog before? If so, please include some links below 👇
https://nordicapis.com/author/thomas_bush/

**Comment by SethuRamanOmanakuttan** [comment]
hey @tster, the idea is pretty neat, but can we have the article focus exclusively on the NFT part, like, "how to mint your first NFT", maybe also introduce the readers to some handy tools and platforms that they can use

**Comment by SethuRamanOmanakuttan** [comment]
hey @tster, the idea is pretty neat, but if I understand it correctly, you are already covering the NFT part in one of your other proposals, so here, can we have the article focus on introducing the different smart contract development processes (including testing, auditing and updation)

**Comment by tster** [comment]
Hi @SethuRamanOmanakuttan, sure. My original intention for [proposal #7](https://github.com/chainstack/developer-hub-content/issues/7) was to discuss interaction with NFT smart contracts through ethers.js, while this guide would demonstrate how to deploy new (NFT) smart contracts. Whether or not I cover NFT smart contracts, I'd be happy to include information about the smart contract creation process in this article.

**Comment by uF4No** [comment]
I think publishing a smart contract is something that we've touched on a few different tutorials already in the blog. 

@tster I like the idea of an article about creating an NFT collection, minting, and transferring them so if you're up to that, we can do it on proposal #7 and close this one.

**Comment by tster** [comment]
> I think publishing a smart contract is something that we've touched on a few different tutorials already in the blog.
> 
> @tster I like the idea of an article about creating an NFT collection, minting, and transferring them so if you're up to that, we can do it on proposal #7 and close this one.

Sure, sounds good!
