### ISSUE TITLE
[PROPOSAL]  Staking 101 - the bare guide

### ISSUE THREAD

**Issue by ankitzm** [chainstack/developer-hub-content#12]
- Content is:
  [ ] Coding tutorial
  [ x ] Informational content
  [ ] Other (describe)

- Which blockchain protocol is this about?:
Not protocol specific

- Description (two or three phrases describing what is it about):
    - All about Staking and why to do it.
    - Pros and Cons of staking.
    - PoW vs PoS 

- Have you published articles in a blog before? If so, please include some links below 👇
    - https://medium.com/0xblocktrain/open-zepplin-what-and-why-7537b1c5ced5
    - https://medium.com/0xblocktrain/layer-0-what-a7eccaab27aa
    - https://medium.com/0xblocktrain/ethereum-token-standards-3d67adfaf9e4
    - https://medium.com/0xblocktrain/defi-fixing-the-current-financial-system-e2db71071438

**Comment by uF4No** [comment]
Hey @ankitzm Thanks for your proposal but we don't think it's a good fit. Feel free to create a new one if you have other ideas 🤙
