### ISSUE TITLE
[PROPOSAL]Understanding Blockchain and smart contract Testing

### ISSUE THREAD

**Issue by Frank-dev20** [chainstack/developer-hub-content#15]
- Content is:

-   [ ] Coding tutorial

-   [ ] Informational content

  [ ] Other (describe)

- Which blockchain protocol is this about?:

1. Ethereum
2. Web3

- Description (two or three phrases describing what is it about):
This guide will explain testing in blockchain and illustrates with code snippets how to test smart contract.

- Have you published articles in a blog before? If so, please include some links below 👇
[Managing Defi transaction with InstaDApp](https://blog.logrocket.com/how-to-manage-defi-transactions-instadapp/)
[Ethereum and Flow](https://blog.logrocket.com/ethereum-flow-blockchain-nft-development/)
[Blockchain with Nodejs](https://blog.logrocket.com/build-cryptocurrency-node-js-blockchain/)
[Python Datetime Module](https://blog.logrocket.com/python-datetime-module-handling-dates-time/)

**Comment by uF4No** [comment]
Hi @Frank-dev20 
We've already covered testing on a few blog posts, but all those are a high-level overview, not a deep dive with full details.
Can you give us more details about what you have in mind? Are you going to use a specific framework or multiple ones? which type of contract(s) would you use as an example?

**Comment by Frank-dev20** [comment]
> Hi @Frank-dev20 We've already covered testing on a few blog posts, but all those are a high-level overview, not a deep dive with full details. Can you give us more details about what you have in mind? Are you going to use a specific framework or multiple ones? which type of contract(s) would you use as an example?

In this article, I will explain what blockchain testing is, the benefit of blockchain testing, challenges with blockchian testing, types and phases of testing. I will also cover tools used for blockchain testing and finally develop a smart contract for an auto tracking system using Truffle nodejs module, and an accompanying test.

**Comment by Frank-dev20** [comment]
@uF4No please any feedback yet concerning this proposal?

**Comment by uF4No** [comment]
Hi @Frank-dev20, we've already explained [testing using Brownie in this article in our blog](https://chainstack.com/the-brownie-tutorial-series-part-2/). If you could focus your article on testing with Foundry, I think it would be a good fit. Does it sound interesting?

**Comment by Frank-dev20** [comment]
> Hi @Frank-dev20, we've already explained [testing using Brownie in this article in our blog](https://chainstack.com/the-brownie-tutorial-series-part-2/). If you could focus your article on testing with Foundry, I think it would be a good fit. Does it sound interesting?

I haven't used Foundry before though.
