### ISSUE TITLE
[PROPOSAL] Introduction to Decentralized Storage 

### ISSUE THREAD

**Issue by oyedeletemitope** [chainstack/developer-hub-content#16]
- Content is:
  [ ] Coding tutorial
  [x] Informational content
  [ ] Other (describe)

- Which blockchain protocol is this about?:
- Storage

- Description (two or three phrases describing what is it about):
In this article, we'll take a look at what decentralized storage is, how it works, its benefits as well as some examples of decentralized storage

- Have you published articles in a blog before? If so, please include some links below 👇
https://blog.logrocket.com/author/temitopeoyedele/
https://codesource.io/author/koded/

**Comment by uF4No** [comment]
Hi @oyedeletemitope 
Can you provide more details? Which protocols would you like to explain? Will you include a small tutorial to use them?

**Comment by oyedeletemitope** [comment]
Hello @uF4No sorry for the late reply. Here’s my outline:

- What is decentralized storage
- How it works
  - shard I get
  - Encryption 
  - Storage
 - The benefits of decentralized storage
This includes:
     - data security 
     - Privacy 
     - Efficiency 
     - Lower cost
  - Decentralized storage networks
  Here I’ll be discussing the common decentralized storage network like
     - siacoin
     - Filecoin
     - Bluzelle
     - Storj
     - arweave
    
 Conclusion

**Comment by Genesis3800** [comment]
Hey @oyedeletemitope ,

We discussed your proposal internally, and we like it. A couple of things we would like to add-

1. When you discuss the different storage protocols, we would like to see their differences being highlighted. As in take a couple of parameres like degree of decentralization and average cost of uploading, and compare them along these lines
2. We would like to see a section added on IPFS.

What do you think of this?

**Comment by oyedeletemitope** [comment]
Hello @uF4No, no problem. I’m okay with it

**Comment by Genesis3800** [comment]
Ok then @oyedeletemitope ,
We wish you the best of luck for the article, and we look forward to what you write :)
I'll be your point of contact moving forward, although Antonio may also talk to you.

If you have any doubts, please tag me, I'll help you out as best I can........

**Comment by oyedeletemitope** [comment]
Thank you @Genesis3800 i’ll get started on this piece and send in my draft once I’m done

**Comment by Genesis3800** [comment]
Hey @oyedeletemitope ,
I'm just checking in to see how you're doing with your first draft? 
Feel free to reach out to me if you're facing problems, we'll try our best to see this through with you.

**Comment by oyedeletemitope** [comment]
Hello @Genesis3800 I have already started working on the article although I’m facing issues regarding the level  part where you stated to add the degree of decentralization in each of them.

**Comment by Genesis3800** [comment]
Hey @oyedeletemitope , what we meant by 'degree of decentralization' was just that you can mention how many nodes a particular protocol is running in the moment.
It is ok if you can't find that information, but we would like to see it if it is listed for a particular protocol.

**Comment by oyedeletemitope** [comment]
Thank you for the clarification @Genesis3800. I'll be sending in my draft soon for reviews.

**Comment by oyedeletemitope** [comment]
Thank you for the clarification @Genesis3800. I'll be sending in my draft soon for review.

**Comment by oyedeletemitope** [comment]
Thank you for the clarification @Genesis3800. I'll be sending in my draft soon for review.

**Comment by oyedeletemitope** [comment]
Thank you for the clarification @Genesis3800. I'll be sending in my draft soon for review.

**Comment by oyedeletemitope** [comment]
Hello @Genesis3800, here’s the draft of the article. Looking forward to your review. Thanks

**Comment by Genesis3800** [comment]
Hey @oyedeletemitope , I don't see a pull request by you in the repo. I think you may have forgotten to do that. Please check on that and get back to me.

**Comment by oyedeletemitope** [comment]
Hello @Genesis3800, i just created one now.
