### ISSUE TITLE
A Detailed Tutorial to Understanding Mapping in Solidity

### ISSUE THREAD

**Issue by johnfawole** [chainstack/developer-hub-content#19]
Proposed topic: A Detailed Tutorial to Understanding Mapping in Solidity
- Content is:
  [ ] Coding tutorial
  [ ] Informational content
  [ ] About Solidity

- Which blockchain protocol is this about? Etheruem

- Description (two or three phrases describing what is it about): I discovered there are not enough content that explains the concept of mapping in solidity. So this tutorial content is an attempt to give a broad overview of mapping for everyone to understand regardless of their levels

- Have you published articles in a blog before? If so, please include some links below 👇
- 1. https://johnfawole.hashnode.dev/community-building-is-the-main-marketing-strategy-in-web3-here-is-why

2. https://mirror.xyz/0x7AbeC848F5D5A07F591cA20011125E3BB6bdE4eD/wshfe7hc6stqSHJfzMRGwPcmmqxkRCIJxNjWhj8Qays 

3. https://medium.com/afripay/afripay-pan-african-cryptocurrency-project-aimed-to-help-small-business-owners-98dc0a7c6dc8

### Proposed Outline

- Introduction
- What is the essence of mapping in Solidity? 
- Analogies to Explain How Mapping Works

- How to Create Mapping in Solidity
- What are the two types of mapping in Solidity?

1. Simple mapping 
2. Nested mapping 

- What are the use cases of mapping in Solidity? 

1. Tracking balances 
2. Tracking Approvals 
3. Identifying owners 

- How Mappings Are Stored in Solidity

- How to Set, Get, Update and Delete Mappings
- How to Work with Arrays in Mapping
- How to Loop Through Mapping
- Iterable mapping

Creating a Custom Contract in Solidity to Explain Mapping 
- here, I will code a simple contract 
- this is where Hardhat comes in; I will test and deploy it with Chainstack API endpoints 

- Summary - Mapping in Solidity

**Comment by Genesis3800** [comment]
Hey @johnfawole , thanks a lot for your interest in our developer hub program.
Can you please edit your issue to include a proposed outline for your article? 

Check out this issue for some inspiration-

[https://github.com/chainstack/developer-hub-content/issues/18](https://github.com/chainstack/developer-hub-content/issues/18)

**Comment by johnfawole** [comment]
Thanks for the update. I'll update it right away. Thanks.

**Comment by johnfawole** [comment]
Alright, I'll be expecting your feedback.

Haha.

**Comment by Genesis3800** [comment]
Hey @johnfawole , We discussed your proposal internally, and everyone wants to see this through. We would however like to modify your proposal in a way that better matches our existing blog posts.
Can we have a google/zoom meet to talk for a bit?

**Comment by johnfawole** [comment]
Oh, that is great.

Yes, sure. I am available. Tell me when you'd be ready to jump on a call.

**Comment by Genesis3800** [comment]
I am available for the next 30 minutes from the time I am writing this. Are you available?

**Comment by johnfawole** [comment]
Great, just dropped you a message.

**Comment by Genesis3800** [comment]
Hey @johnfawole , thanks for updating the outline. 
We would love to see the testing and deployment of your demo smart contract using Hardhat's latest practices.
I like the outline, and I am excited to inform you that your proposal has been accepted.

If you need any help with your article, feel free to reach out.

**Comment by johnfawole** [comment]
Awesome, thanks for the update!

**Comment by Genesis3800** [comment]
Hey @johnfawole ,
Thank you for your PR.

Here is what the process will look like moving on.

1. I'll review your code and article in the next few days and work with you to fine-tune the article per our requirements.
2. Once that is done, I will pass on your article internally for a peer review. This is the final review stage. Once this is done, we will merge the PR and will begin the process of publishing which might take up to a month.
3. You will be paid as soon as your article is accepted internally (after step 2). 

We look forward to working with you to take your work to the finish line.

**Comment by johnfawole** [comment]
Awesome, thanks for the update!

**Comment by johnfawole** [comment]
Hi Priyank, I have adjusted the content as you required.

Please, check. Thanks.

**Comment by Genesis3800** [comment]
I'll have a look and get back to you @johnfawole . Thanks for updating the commit.

**Comment by Genesis3800** [comment]
Hey @johnfawole ,
Thank you for your contribution to the developer hub.
We appreciate having you with us.
To move forward, please send me your email address. 

I will reach out to you via mail to request your bank details for processing your payment.

**Comment by johnfawole** [comment]
It's my pleasure, Priyank.

Here is my Gmail - ***@***.***

Thanks.

**Comment by Genesis3800** [comment]
Hey @johnfawole ,
this is what I see as your email. 
![image](https://user-images.githubusercontent.com/56264430/208414620-52cc12b9-1c3e-446c-b406-c010d06fb761.png)

**Comment by johnfawole** [comment]
Wow, how come?

This is it again - johnfawole18@gmail.com

**Comment by Genesis3800** [comment]
Cool. I'll reach out to you over there.
