### ISSUE TITLE
[PROPOSAL]

### ISSUE THREAD

**Issue by dc199411** [chainstack/developer-hub-content#2]
- Content is: MULTIVERSE TOKEN
[pragma solidity 0.6.12;

import "../OpenZeppelin/access/AccessControl.sol";
import "./ERC20/ERC20Burnable.sol";
import "./ERC20/ERC20Pausable.sol";
import "../interfaces/IMisoToken.sol";

// ---------------------------------------------------------------------
//
// From the MISO Token Factory
//
// Made for Sushi.com 
// 
// Enjoy. (c) Chef Gonpachi 2021 
// <https://github.com/chefgonpachi/MISO/>
//
// ---------------------------------------------------------------------
// SPDX-License-Identifier: GPL-3.0                        
// ---------------------------------------------------------------------

contract MintableToken is AccessControl, ERC20Burnable, ERC20Pausable, IMisoToken {
    
    /// @notice Miso template id for the token factory.
    /// @dev For different token types, this must be incremented.
    uint256 public constant override tokenTemplate = 2;

    bytes32 public constant MINTER_ROLE = keccak256("MINTER_ROLE");
    bytes32 public constant PAUSER_ROLE = keccak256("PAUSER_ROLE");

    function initToken(string memory _name, string memory _symbol, address _owner, uint256 _initialSupply) public {
        _initERC20(_name, _symbol);
        _setupRole(DEFAULT_ADMIN_ROLE, _owner);
        _setupRole(MINTER_ROLE, _owner);
        _setupRole(PAUSER_ROLE, _owner);
        _mint(msg.sender, _initialSupply);
    }

    function init(bytes calldata _data) external override payable {}

   function initToken(
        bytes calldata _data
    ) public override {
        (string memory _name,
        string memory _symbol,
        address _owner,
        uint256 _initialSupply) = abi.decode(_data, (string, string, address, uint256));

        initToken(_name,_symbol,_owner,_initialSupply);
    }

   /** 
     * @dev Generates init data for Token Factory
     * @param _name - Token name
     * @param _symbol - Token symbol
     * @param _owner - Contract owner
     * @param _initialSupply Amount of tokens minted on creation
  */
    function getInitData(
        string calldata _name,
        string calldata _symbol,
        address _owner,
        uint256 _initialSupply
    )
        external
        pure
        returns (bytes memory _data)
    {
        return abi.encode(_name, _symbol, _owner, _initialSupply);
    }

    /**
     * @dev Creates `amount` new tokens for `to`.
     *
     * See {ERC20-_mint}.
     *
     * Requirements:
     *
     * - the caller must have the `MINTER_ROLE`.
     */
    function mint(address to, uint256 amount) public virtual {
        require(hasRole(MINTER_ROLE, _msgSender()), "MintableToken: must have minter role to mint");
        _mint(to, amount);
    }

    /**
     * @dev Pauses all token transfers.
     *
     * See {ERC20Pausable} and {Pausable-_pause}.
     *
     * Requirements:
     *
     * - the caller must have the `PAUSER_ROLE`.
     */
    function pause() public virtual {
        require(hasRole(PAUSER_ROLE, _msgSender()), "MintableToken: must have pauser role to pause");
        _pause();
    }

    /**
     * @dev Unpauses all token transfers.
     *
     * See {ERC20Pausable} and {Pausable-_unpause}.
     *
     * Requirements:
     *
     * - the caller must have the `PAUSER_ROLE`.
     */
    function unpause() public virtual {
        require(hasRole(PAUSER_ROLE, _msgSender()), "MintableToken: must have pauser role to unpause");
        _unpause();
    }

    function _beforeTokenTransfer(address from, address to, uint256 amount) internal virtual override(ERC20, ERC20Pausable) {
        super._beforeTokenTransfer(from, to, amount);
    }
} ] Coding tutorial

[MULTIVERSE TOKEN IS A MULTICHAIN TOKEN DESIGNED TO BE THE FOUNDATION FOR THE BIGGEST METAVERSE PROJECT EVERY APTLY NAMED MULTIVERSE THAT TAKES EVER METAVERSE PROJECT AND GAME AND INTEGRATES IT INTO A VR/AR MULTIVERSE HUB LIKE THE OASIS FROM THE 2018 MOVIE READY PLAYER ONE

help create tomorrow's future a small startup named COIN2CASH SPEAR HEADED By me are developing what we are calling the MULTIVERSE In the MULTIVERSE you will be able to interact with explore play and earn real cryptocurrency from your favortie metaverse project/nft game on your Blockchain of choice have you ever watched the movie "ready player one" that is the true metaverse an interconnected universe nay MULTIVERSE were everyone can enjoy until there hearts content and still not have seen everything to do and all the ways to earn crypto/money and nft/charcters and items the list is endless me and my team have been hard at work developing some truly amazing things to mover closer toward a united yet decatralized MULTIVERSE We at C2C Are well on our way and almost ready for metaverse project/game inetgrations into our MULTIVERSE to many companies are developing metaverse projects trying to beat the competition and are not worried about or considering what the world wants and dont know they need to worried about making money and beating competitors the metaverse is a not only a way to meet with friends from around the world a place to socialize with everyone a way for people to feel truly connected a home away from home per say but also a way to earn a decent living via shops owned by individuals galleries to sell nft artwork and basically anything in between if its in real life it will be in the metaverse or shall i say MULTIVERSE We at C2C have already launched initial DEX offerings via sushiswap's newly launched MISO PLATFROM the IDO'S are being held on low fee Blockchains such as Binance smart chain moonriver and harmony one with polygon next and more just around the corner at C2C we know what the metaverse should be and what it can be when everyone joins together to build as a whole yet decntralized manner we will soon be launching our C2CDao for true decatralizarion with a twist our governance model will be based off of affordable NFT'S Were the version or style of NFT you own will give each user a set number of votes the number will be initially be set my our team but after launch any owning an initial NFT WILL be able to propose different NFT'S As well as the amount of votes said NFT'S Should hold this is the begining of tomorrow's future the metaverse as you know it is to soon change forever we will update as much as possible and provide our roadmap in the very near future dont want for tomorrow create tomorrow be the decider of your own fate and CLAIM a piece of the MULTIVERSE as your own ! we at C2C Greatly appreciate each and every person/creator and so should the world stand with us as we UNITE THE METAVERSE. metaverse project integration announcements and MULTIVERSE TOKEN listings soon ] Informational content

https://nomics.com/assets/mv3-multiverse#about

https://github.com/dc199411/multiverse

- Description (two or three phrases describing what is it about):
METAVERSE NFT GAMEFI PROJECT

**Comment by uF4No** [comment]
This proposal does not follow the [content requirements](https://github.com/chainstack/developer-hub-content#content-requirements)
