### ISSUE TITLE
[PROPOSAL]

### ISSUE THREAD

**Issue by NecheyGrace** [chainstack/developer-hub-content#21]
- Content is:
  [ ] DAOs and voting 
  [ ] How DAOs work and voting 
  [ ] Other (describe)

- Have you published articles in a blog before? If so, please include some links below 👇
https://hashnode.com/@Nechey

**Comment by NecheyGrace** [comment]
Waiting for response

**Comment by Genesis3800** [comment]
Hey @NecheyGrace , thank you for your interest in our developer hub program. 
Before I pass on your proposal for an internal vote, could you please elaborate on your proposal a bit?
Specifically, I would really like to see an article outline/table of contents.

Check this out for some inspiration-
https://github.com/chainstack/developer-hub-content/issues/18
