### ISSUE TITLE
[PROPOSAL] How to build a Forta bot for your smart contract

### ISSUE THREAD

**Issue by yehia67** [chainstack/developer-hub-content#22]
- Content is:
  [x] Coding tutorial
  [ ] Informational content
  [ ] Other (describe)

- Which blockchain protocol is this about?:
Multichain
- Description (two or three phrases describing what is it about):
[Forta](https://docs.forta.network/en/latest/what-is-forta) is a monitor bot to detect threads on your smart contract. In this tutorial, you will learn how to develop, test, and deploy a bot to keep track of every transaction, block, or triggered event from your smart contract and receive an email as an alert from it.
- Have you published articles in a blog before? If so, please include some links below 👇
https://medium.com/coinmonks/recycling-system-using-iota-2172ecc7444
https://medium.com/coinmonks/eco-track-supply-chain-and-recycling-services-using-iota-c2b1de681aac
https://medium.com/coinmonks/uniswap-fork-web3-with-react-hooks-and-redux-ed407abffbc8

Outline: 
1. Introduction:
       - What is a Forta bot?
       - Forta Bot use cases.
2. Initialize your Forta project.
3. Forta package command lines.
4. Detect smart contract activities by transaction, block, or event.
5. Build alert reports with customized data and categories(Crucial, Suspicious, and info). 
6. Test your Forta bot.
7. Deploy bot to different blockchains protocols
8. References: 
  - GitHub repository with the article example.
  - Documentation.
  - Forta bot examples

**Comment by Genesis3800** [comment]
Hey @yehia67, thank you for your interest in our developer hub program.
Before I pass on your proposal for an internal vote, could you please elaborate on your proposal a bit?
Specifically, I would really like to see an article outline/table of contents.

https://github.com/chainstack/developer-hub-content/issues/18

**Comment by Genesis3800** [comment]
Hey @yehia67 , an update for you. We are really interested in publishing an article on Forta for our blog. We discussed this internally and liked it.
Before approving the issue however, we would really like to see a proposed outline. Could you please update the issue a little? 
This will also help you in better fleshing out your article in your mind.

**Comment by yehia67** [comment]
@Genesis3800  I am happy to hear that 😄  Updated 👍

**Comment by Genesis3800** [comment]
Thanks for updating the issue @yehia67 , I love the way it looks.
Just one final question- As I understand you will teach people how to use Fortabot to interact with smart contracts, will you write a sample smart contract as an example to demonstrate the bot's use case as part of the article?

**Comment by yehia67** [comment]
Yes exactly

**Comment by yehia67** [comment]
It will be a deposit smart contract 
If blacklisted addresses deposit it will trigger a critical alert.
If normal deposit will trigger info alert.
If less then 0.0001 will trigger suspicious

**Comment by Genesis3800** [comment]
Hey @yehia67 , this sounds really cool.
I am changing the issue label to in progress, in other words, your proposal has been accepted. 
Best of luck with this article. I look forward to reading your first draft.

**Comment by yehia67** [comment]
I am so excited🚀

**Comment by Genesis3800** [comment]
Hey @yehia67 ,

Thank you for your PR.

Here is what the process will look like moving on.

1. I'll review your code and article in the next few days and work with you to fine-tune the article per our requirements.
2. Once that is done, I will pass on your article internally for a peer review. This is the final review stage. Once this is done, we will merge the PR and will begin the process of publishing which might take up to a month.
3. You will be paid as soon as your article is accepted internally (after step 2). 

We look forward to working with you to take your work to the finish line.

**Comment by yehia67** [comment]
Sounds great!😄

**Comment by Genesis3800** [comment]
HEy @yehia67 ,
I want you to know that I am actively reviewing them all. Will leave comments as soon as possible. 
By the way, are you on our discord server? 

I recommend you join our developer hub channel to keep up to date.

https://discord.gg/Cymtg2f7pX

**Comment by yehia67** [comment]
Hey hey, Thank you @Genesis3800 looking forward to your comments! I joined the dicord server and droped a message on the developer hub channel👍
