### ISSUE TITLE
[PROPOSAL] Proof of Work vs Proof of Stake

### ISSUE THREAD

**Issue by dpkreativ** [chainstack/developer-hub-content#23]
- Content is:
  [ ] Coding tutorial
  [x] Informational content
  [ ] Other (describe)

- Which blockchain protocol is this about?:
Ethereum

- Description (two or three phrases describing what it is about):
One of the most discussed events in blockchain conversations is the recent Ethereum Merge, upgrading from a Proof-of-Work mechanism to Proof-of-Stake. 
In this article, the reader will learn about these two concepts and understand their history, strengths, weaknesses, similarities, and differences.

- Have you published articles in a blog before? If so, please include some links below 👇
[Token standards introduction: ERC-20, ERC-777, ERC-721, and ERC-1155](https://chainstack.com/token-standards-intro-erc20-erc777-erc721-erc1155/)

### Proposed Outline
- Introduction(_Give a little background intro on conversations surrounding Proof of Work and Proof of Stake_)
- Proof of Work (_Talk about Proof of Work's concept. Its origins, major use-cases, strengths, and downsides_)
- Proof of Stake (_Talk about Proof of Stake's concept. Its origins, use-cases, strengths, and downsides_)
- Similarities and Differences (_Comparisons between both consensus mechanisms_)
- Final Thoughts (_Article's conclusion, talking about current and expected trends in the blockchain space regarding consensus mechanisms_)

**Comment by dpkreativ** [comment]
Hi @Genesis3800! I hope your day is going well.
I would like to write about this. 
Please let me know if I should proceed with it. Thanks

**Comment by Genesis3800** [comment]
Hey @dpkreativ ,
I am doing well, thanks a lot. 
We loved your first article with us, but we have only just published an article on the Merge on our blog and are not looking to add any more articles on Ethereum's consensus model. Please feel free to submit more proposals as you see fit.

**Comment by dpkreativ** [comment]
That's fine. Thank you.
