### ISSUE TITLE
[PROPOSAL] The benefit of decentralizing your web3 Infrastructure

### ISSUE THREAD

**Issue by nickatnight23** [chainstack/developer-hub-content#24]
- Content is:
  [ x] Coding tutorial
  [x ] Informational content
  [ ] Other (describe)

- Which blockchain protocol is this about?:
- Node Provider POKT

- Description (two or three phrases describing what is it about):
POKT is a decentralized node provider. Introducing the community to POKT and showing how to decentralize your Metamask.
- Have you published articles in a blog before? If so, please include some links below 👇
https://dev.to/tricadev23/block-chain-989

Outline Proposed:
Describe POKT
Benefits of using POKT
Tutorial on how to decentralize  Metamask
Conclusion
Resources

**Comment by Genesis3800** [comment]
Hey @nickatnight23  , we discussed your proposal internally, and unfortunately, we are not looking to add any articles on web3 infrastructure to our blog for now.
We hope to have you around and pitch new ideas for our blog though :)
