### ISSUE TITLE
[PROPOSAL] DeFI - Understanding the DEX orderbook

### ISSUE THREAD

**Issue by ioablock** [chainstack/developer-hub-content#25]
- Content is:
  [x ] Coding tutorial
Creating a rest api in nodejs and typescript that computes the execution price of a given amount of crypto (BTC-USDT) from the orderbooks of DYDX (a DEX orderbook)
  [x ] Informational content
Explaining what is a DEX Orderbook, and the difference with a DEX AMM
  [ ] Other (describe)

- Which blockchain protocol is this about?:
Ethereum
- Description (two or three phrases describing what is it about):
The content:
1. Explaining what is a DEX Orderbook, and the difference with a DEX AMM
2. Explaining crypto exchange concepts: order book, bid, ask, liquidity, slippage
3.  Coding tutorial of a rest api in nodejs and typescript that computes the best execution price of a given amount of crypto (BTC-USD) from the order books of  DYDX

- Have you published articles in a blog before? If so, please include some links below 👇
Haven't published before, I'm excited to begin writing technical content.

**Comment by Genesis3800** [comment]
Hey @ioablock , we discussed your proposal internally, and we really like it.
We are looking to put more coding tutorials on our blog, and yours seems to be a good addition.
However, we would like to get some details regarding your article before proceeding further.

Can we schedule an online call sometime to talk?

**Comment by ioablock** [comment]
Hello! Yes, of course. You can add me on discord: chukae#7487, so that we can schedule the online call

**Comment by Genesis3800** [comment]
Sent you a request via SoulGenesis (He/Him)#9153

**Comment by ioablock** [comment]
I accepted the request.

**Comment by ioablock** [comment]
I can change the tutorial to calculate the execution price on DYDX - DEX with order book.

**Comment by Genesis3800** [comment]
Hey @ioablock ,
This sounds really interesting. I love the concept of fetching the price from a decentralized orderbook. I'll run this revised proposal internally ASAP and get back to you.

**Comment by Genesis3800** [comment]
Hey @ioablock ,
I am excited to inform you that your proposal has been excited. We really like it and look forward to seeing your first draft.
I am changing the status of this issue.

**Comment by ioablock** [comment]
Amazing! Could you confirm that once I write the draft, I attach it here?

**Comment by Genesis3800** [comment]
Hey @ioablock ,
you can look at the repo's readme for the exact instructions to submit an article. That should be better than any explanation I can give you in here
