### ISSUE TITLE
[PROPOSAL] Handle Image Uploads on Ethereum Using IPFS

### ISSUE THREAD

**Issue by dpkreativ** [chainstack/developer-hub-content#29]
- Content is:
  [x] Coding tutorial
  [ ] Informational content
  [ ] Other (describe)

- Which blockchain protocol is this about?:
Ethereum

- Description (two or three phrases describing what it is about):
In this article, the reader will learn how to set up IPFS (Interplanetary File System) on a DApp and store images. At the end of this article, the reader will gain more insight into how decentralized storage works and how to take advantage of it.

- Have you published articles in a blog before? If so, please include some links below 👇
https://chainstack.com/token-standards-intro-erc20-erc777-erc721-erc1155/

**Comment by Genesis3800** [comment]
Hey @dpkreativ ,
Thank you for your proposal. 
Most of the Chainstack team is at Bogota right now, which makes an internal vote on your proposal difficult. 
I will get back to you as soon as possible.
We appreciate having you with us, and look forward to you publishing another article with us.

**Comment by Genesis3800** [comment]
Hey @dpkreativ ,
Sorry to keep you waiting. The team has just now assembled after DEVCON, and we had an internal discussion about your proposal.
Unfortunately, we are not looking for articles on IPFS right now.
We love to have you here and look forward to any proposals you might submit in the future.

**Comment by dpkreativ** [comment]
That's okay @Genesis3800
thanks for the feedback
