### ISSUE TITLE
[PROPOSAL] The Graph Protocol For Smart Contracts Querying Data

### ISSUE THREAD

**Issue by yehia67** [chainstack/developer-hub-content#31]
- Content is:
  [x] Coding tutorial
  [ ] Informational content
  [ ] Other (describe)

- Which blockchain protocol is this about?:
Multi-chain

- Description (two or three phrases describing what is it about):
What is the subgraph? Why use It, and how? and How to create a subgraph for your smart contracts
Outline:
- Introduction about the graph protocol. What and why
- Demonstrate Uniswap subgraph on subgraph studio.
- Learn how to query data.
- How to connect the subgraph to your front-end website.
- Build your own subgraph.
- Deploy your subgraph.

- Have you published articles in a blog before? If so, please include some links below 👇
https://medium.com/coinmonks/recycling-system-using-iota-2172ecc7444
https://medium.com/coinmonks/eco-track-supply-chain-and-recycling-services-using-iota-c2b1de681aac
https://medium.com/coinmonks/uniswap-fork-web3-with-react-hooks-and-redux-ed407abffbc8

**Comment by Genesis3800** [comment]
Hey @yehia67 ,
We are taking a look at your latest Fortabot commit internally, and will be having a discussion about your latest proposal too.
Thank you for your patience. We love having you with us. Will get back to you as soon as I can.

**Comment by Genesis3800** [comment]
Hey @yehia67 ,
We discussed your proposal internally, and we would like to move ahead on it. I am accepting the proposal, and am looking forward to your first draft.

**Comment by yehia67** [comment]
@Genesis3800 Great! I will start right away 🏃
