### ISSUE TITLE
[PROPOSAL] Playing around with AMM Invariants

### ISSUE THREAD

**Issue by legion2002** [chainstack/developer-hub-content#32]
- Content is:
  [ ] Coding tutorial
  [x ] Informational content
  [ ] Other (describe)

- Which blockchain protocol is this about?:
Ethereum

- Description (two or three phrases describing what is it about):
- An informational article aiming at giving an intuitive understanding of how AMM invariants work and building fundamentals to DEXes. The article will achieve this by creating toy AMM invariants on desmos, discussing pricing, usecases, innovations in the field etc. It will end with discussing other popular constant function market makers like Uniswap V2, Stable swap etc.

- Have you published articles in a blog before? If so, please include some links below 👇
https://metaschool.so/course/launch-your-own-epic-nft-marketplace

Some articles which are not public yet, but I can give access to them privately- 
1. Informational article on common smart contract security vulnerabilities
2. Coding Tutorial on building a toy DAO from scratch

**Comment by legion2002** [comment]
> Hey @legion2002 , hope you're keeping well. 
> 
> I would like to apologize for being so delayed in getting back to you. I just realized I haven't been getting issue notifications from this repo.
> 
> We really appreciate having you with us.
> 
> If you're still interested in publishing with us, I will take up your proposal internally and get back as soon as I can.
> 
> Looking forward to hearing back from you. 

Hey @Genesis3800,
Nice to hear back, yeah sure I am still up for building this, probably in about 2 weeks or so.

**Comment by Genesis3800** [comment]
Hey @legion2002,
thanks a lot for proposing an issue on the developer hub.
We really appreciate having you here.
Unfortunately, we are not as of now looking to add content specific to your proposal.
I am closing this issue, but please feel free to make new ones.
