### ISSUE TITLE
[PROPOSAL] Comparison between Daml and Solidity

### ISSUE THREAD

**Issue by kimkimani** [chainstack/developer-hub-content#34]
- Content is:
  [ ] Coding tutorial
  [ ] Informational content
  [ ] Other (describe)

Which blockchain protocol is this about?:

Daml and Solidity

Description (two or three phrases describing what is it about):

- Solidity Overview
- Daml Overview
- Why would businesses use it instead of Ethereum
- Business usecase example

Have you published articles in a blog before? If so, please include some links below 👇

- https://www.section.io/engineering-education/authors/joseph-chege/
- https://blog.logrocket.com/author/josephkimani/
- https://mattermost.com/blog/how-to-deploy-a-react-app-to-kubernetes-using-docker/
- https://www.webiny.com/blog/build-notes-app-nextjs-webiny-headless-cms
- https://medusajs.com/blog/how-to-integrate-live-chat-with-gatsby-tidio-medusa/
- https://www.webiny.com/blog/build-todo-app-flutter-webiny-headless-cms
- https://strapi.io/blog/how-to-build-a-blog-app-with-remix-and-strapi-cms

**Comment by Genesis3800** [comment]
Thank you for your proposal @kimkimani. I will take this up internally and get back to you as soon as I can.
We appreciate having you with us :)

**Comment by Genesis3800** [comment]
Hey @kimkimani ,

thanks a lot for proposing an issue on the developer hub.
We really appreciate having you here.
Unfortunately, we are not as of now looking to add content specific to your proposal.
I am closing this issue, but please feel free to make new ones.
