### ISSUE TITLE
[PROPOSAL]

### ISSUE THREAD

**Issue by extravaganza77** [chainstack/developer-hub-content#35]
- Content is:
  [ ] Coding tutorial
  [X] Informational content
  [ ] Other (describe)

- Which blockchain protocol is this about?:
- 
Understanding Blockchains Interoperability via Cosmos Network

### Introduction
The adoption of crypto is still facing challenges. Its adoption is slow compared to the global users of the internet. The [blockchains](https://www.ibm.com/topics/what-is-blockchain) will still face the challenge of slow adoption because they lack [interoperability](https://www.gemini.com/cryptopedia/why-is-interoperability-important-for-blockchain). Different methods have been devised to achieve interoperability between the blockchains. However, most exchanges only operate between two blockchains.

Most interoperability approaches do not impact network efficiency, upgradeability, and sustainability. In an attempt to address these issues, [cosmos networks](https://forkast.news/what-is-cosmos-the-internet-of-blockchains/) provide a way to achieve interoperability. This article will examine the cosmos network in achieving interoperability between blockchains.

### Overview of cosmos network
Cosmos network refers to the architecture that enables different blockchains to communicate and exchange data. The main aim of the cosmos network is to develop a network where blockchains will do away with computers. For this reason, different blockchains will no longer compete as they will work in the same environment.

An independent design method is followed when developing blockchains in the cosmos environment. The design method ensures that the [application layer](https://coinmarketcap.com/alexandria/article/what-are-application-layer-protocols) is independent of the [consensus](https://www.coindesk.com/markets/2017/03/04/a-short-guide-to-blockchain-consensus-protocols/) and [networking](https://www.researchgate.net/figure/The-network-layer-of-a-blockchain-system-is-characterized-by-the-P2P-network-topology_fig1_327484523) layers. Thus, developers can create custom applications based on their preferences and flexibility.

Furthermore, the cosmos network makes application development easy since it offers the required tools and platforms. Therefore, developers can use existing blockchains in the cosmos network to ensure its liquidity and adoption over the shortest time possible.

- Have you published articles in a blog before? If so, please include some links below 👇
1. https://newtonosage.hashnode.dev/how-to-create-a-rest-api-using-spring-boot-maven-and-mysql
2. https://newtonosage.hashnode.dev/building-an-outlook-clone-with-react
3. https://www.section.io/engineering-education/authors/newton-osage/

**Comment by Genesis3800** [comment]
Hey @extravaganza77 , thank you for creating a proposal.
Can you please elaborate on what you plan to include in your article since this does not seem like a coding tutorial?
What exactly are you going to build?

**Comment by Genesis3800** [comment]
Hey @extravaganza77 , 
thanks a lot for proposing an issue on the developer hub.
We really appreciate having you here.
Unfortunately, we are not as of now looking to add content specific to your proposal.
I am closing this issue, but please feel free to make new ones.
