### ISSUE TITLE
 Brownie vs Foundry

### ISSUE THREAD

**Issue by prince-joel** [chainstack/developer-hub-content#38]
- Content is:
  [ ] Informational content

- Which blockchain protocol is this about?: 

They are developing and testing frameworks for the Blockchain.

- Description (two or three phrases describing what is it about): 

Brownie and Foundry are developing and testing frameworks for the Blockchain. They are built for developers who use Python and Solidity respectively.

In this article, the reader will learn what Brownie and foundry are, the difference between Brownie and Foundry, the similarities between brownie and Foundry, and which framework to use and why.

- Have you published articles in a blog before? If so, please include some links below 👇

Yes, I have. Here are some links to my published works.

[Piggy bank](https://dev.to/princejoel/building-a-piggy-bank-smart-contract-with-solidity-hka) 

[Section](https://www.section.io/engineering-education/implementing-totp-2fa-using-flask/) 

[Refine](https://refine.dev/blog/framer-motion-react-animations/)

**Comment by Genesis3800** [comment]
Thank you for your proposal @prince-joel. I will take this up internally and get back to you as soon as I can.
We appreciate having you with us :)

**Comment by prince-joel** [comment]
> Thank you for your proposal @prince-joel. I will take this up internally and get back to you as soon as I can. We appreciate having you with us :)

Thank you @Genesis3800

**Comment by Genesis3800** [comment]
Hey @prince-joel , 

thanks a lot for proposing an issue on the developer hub.
We really appreciate having you here.
Unfortunately, we are not as of now looking to add content specific to your proposal.
I am closing this issue, but please feel free to make new ones.
