### ISSUE TITLE
[PROPOSAL]

### ISSUE THREAD

**Issue by Aysha-py** [chainstack/developer-hub-content#39]
- Content is:
  [ ] Coding tutorial
  [x ] Informational content
  [ ] Other (describe)

- Which blockchain protocol is this about?:
- Ethereum network via Binance and openSea (or any other marketplace platform you want)

- Description (two or three phrases describing what is it about):
- As a person interested in the web3 space, I've asked myself why NFTs generate so much and how it values so much over time. After some research, this article will be based on providing a simplified overview of NFTs and its concepts such as marketplaces and creators. This article will be so detailed and simplified that even web3 newcomers will be able to understand it.

- Have you published articles in a blog before? If so, please include some links below 👇
- https://ayeesh.hashnode.dev/the-buzzword-that-is-everywhere-a-simplified-overview-of-web3-blockchain-and-its-use-cases
- https://ayeesh.hashnode.dev/the-confusing-aspects-of-web3-called-nfts

**Comment by Genesis3800** [comment]
Thank you for your proposal @Aysha-py . I will take this up internally and get back to you as soon as I can.

**Comment by Genesis3800** [comment]
Hey @Aysha-py ,

thanks a lot for proposing an issue on the developer hub.
We really appreciate having you here.
Unfortunately, we are not as of now looking to add content specific to your proposal.
I am closing this issue, but please feel free to make new ones.
