### ISSUE TITLE
Simple Investment Wallet Smart Contract with Solidity

### ISSUE THREAD

**Issue by prince-joel** [chainstack/developer-hub-content#42]
- Content is:
  [ ] Coding tutorial
  [ ] Informational content
  
- Which blockchain protocol is this about?:
   Ethereum

- Description (two or three phrases describing what it is about):
In this article, you will learn how to build a safe investment wallet smart contract with solidity. This wallet only accepts ether, automatically invests 10 percent of every deposit, and gives interest after it matures. You will also learn about the advantages and disadvantages of using a smart contract for fintech projects. By the end of this tutorial, you will learn to write an investment wallet smart contract.

- Have you published articles in a blog before? If so, please include some links below 👇
https://dev.to/princejoel/building-a-piggy-bank-smart-contract-with-solidity-hka
https://www.section.io/engineering-education/implementing-totp-2fa-using-flask/
https://www.section.io/engineering-education/task-tracker-app-with-react-hooks/

**Comment by Genesis3800** [comment]
Hey @prince-joel , thanks a lot for proposing an issue on the developer hub.
We really appreciate having you here.
Unfortunately, we are not as of now looking to add content specific to your proposal.
I am closing this issue, but please feel free to make new ones.
