### ISSUE TITLE
Layer 2 scaling solutions 

### ISSUE THREAD

**Issue by oyedeletemitope** [chainstack/developer-hub-content#43]
Layer 2 scaling solutions exist as a way for blockchains to increase the amount of work they can accomplish. They help improve speed and efficiency of the blockchain. I this proposed article, I’ll discuss 4 main solutions in layer2(Rollups, side chains, channels and plasma)

**Ouline**
- Introduction 
- What are layer 2 scaling solutions 
- Why are they important 
- Layer 2 scaling solutions 
- Conclusion

**Comment by Genesis3800** [comment]
Hey @oyedeletemitope , thanks a lot for proposing an issue on the developer hub.
We really appreciate having you here. 
Unfortunately, we are not as of now looking to add content specific to your proposal.
I am closing this issue, but please feel free to make new ones.
