### ISSUE TITLE
Introduction to Ethereum Rollups

### ISSUE THREAD

**Issue by Chukslord1** [chainstack/developer-hub-content#44]
- Content is:
  [ ] Informational content
  [ ] Other (describe)

- Which blockchain protocol is this about?:
 Ethereum

- Description (two or three phrases describing what it is about):
 In this article, you will learn about  Rollups, the different types of Rollups, such as zero-knowledge rollups, and optimistic rollups, and how they contribute to the scalability of the blockchain. You will also learn about the advantages and disadvantages of rollups. By the end of this tutorial, you will understand the concept of rollups as a scaling solution, why they are important to the blockchain, and when they can be used.

- Have you published articles in a blog before? If so, please include some links below 👇 
* https://blog.logrocket.com/using-plotly-react-build-dynamic-charts-graphs/ 
 
* https://blog.logrocket.com/intro-python-dictionaries/
 
* https://blog.logrocket.com/python-developers-guide-react/
 
* https://arctype.com/blog/mysql-advanced-queries/
 
* https://loft.sh/blog/9-tools-every-platform-engineer-should-know/
 
* https://dev.to/chukslord1/building-an-appointment-scheduler-app-with-django-and-fauna-2n9o

**Comment by Genesis3800** [comment]
Hey @Chukslord1 , thanks a lot for proposing an issue on the developer hub.
We really appreciate having you here.
Unfortunately, we are not as of now looking to add content specific to your proposal.
I am closing this issue, but please feel free to make new ones.
