### ISSUE TITLE
[PROPOSAL] Understand storage layout in smart contracts | How can you read private data in the blockchain? 

### ISSUE THREAD

**Issue by yasmine9** [chainstack/developer-hub-content#45]
- **Content is:**
  [x] Coding tutorial
  [ ] Informational content
  [ ] Other (describe)

- **Which blockchain protocol is this about?:**
General topic, applies for all EVM compatible chains. 

- **Description (two or three phrases describing what is it about):**
This article will be an explanation of the storage layout in a smart contract with a focus on how to read it using a script.
  - What is the storage layout? Can we read private variables too?! 
  - What is a memory slot - simply explained. 
  - How are different variables stored in solidity. 
  - Practical part: 
        - tip: tools to get the slot where the variables are stored 
        - Code: Walkthrough a script about How to practically interact with any smart contract and read any variable you want. From a simple `uint256` or `address` variable to some nested types. 
    -  The article will also point out use cases and the importance of understanding the storage layout in solidity smart contracts. 
    
- **Have you published articles in a blog before? If so, please include some links below** 👇
I usually write some internal tutorials/ helpers in my company for interns. Haven't started writing publicly, I am willing to start putting my writing hobby to contribute here.

**Comment by Genesis3800** [comment]
Hey @yasmine9 ,
Thank you for your proposal to the developer hub.
Apologies for being so late to reply. 
Unfortunately, we are not looking to add informational content along these lines to our blog right now.
Feel free to propose more issues.
