### ISSUE TITLE
Security - Understanding Smart Contract Auditing and its tools

### ISSUE THREAD

**Issue by prince-joel** [chainstack/developer-hub-content#46]
- Content is:
  [ ] Informational content
  [ ] Other (describe)

- Which blockchain protocol is this about?:
 All Blockchain

- Description (two or three phrases describing what it is about):
In this article, you will learn about  Smart Contract Auditing, the different types of Smart Contract Auditing tools, the categories in which these tools fall, and how Smart Contract Auditing is important to the security of the blockchain. You will also learn about the advantages and disadvantages of Smart Contract Auditing. By the end of this tutorial, you will have a better understanding of what Smart Contract Auditing is, why it is crucial for the security of your smart contract, and why you should invest in it as a firm or developer.

- Have you published articles in a blog before? If so, please include some links below 👇
https://dev.to/princejoel/building-a-piggy-bank-smart-contract-with-solidity-hka
https://www.section.io/engineering-education/implementing-totp-2fa-using-flask/
https://refine.dev/blog/framer-motion-react-animations/

**Comment by Genesis3800** [comment]
Hey @prince-joel ,
Thank you for your proposal to the developer hub.
Apologies for being so late to reply.
Unfortunately, we are not looking to add informational content along these lines to our blog right now.
Feel free to propose more issues.
