### ISSUE TITLE
[PROPOSAL]web 3 domain services 

### ISSUE THREAD

**Issue by oyedeletemitope** [chainstack/developer-hub-content#47]
- Content is:
  [ ] Coding tutorial
  [x] Informational content
  [ ] Other (describe)

- Which blockchain protocol is this about?:

- Web3 domains, also known as NFT domains, are blockchain-based versions of DNS addresses that have a variety of uses. One of the main advantages of Web3 domains is that they are decentralized and can be bought and sold like NFTs. In this article, we will explore the concept of Web3 domains.
**Outline:**
- introduction
- What are web 3 domains
- Uses of web 3 domains
- Advantages of web 3 domains 
- Examples of web3 domain name services
This section will contain a list of some web 3 domain name services they include:
- unstoppable 
- Ethereum name services 
- Polkadot name system
- handshake
- Near name
- Algornad
- Telos
- Bonfida

and many more. 

- Have you published articles in a blog before? If so, please include some links below 👇

**Comment by Genesis3800** [comment]
Hey @oyedeletemitope ,
Thank you for your proposal to the developer hub.

Unfortunately, we are not looking to add informational content along these lines to our blog right now.
Feel free to propose more issues.
