### ISSUE TITLE
An overview of decentralized exchanges and how they work

### ISSUE THREAD

**Issue by TheGhoulRe** [chainstack/developer-hub-content#48]
- Content is:
  [ ] Coding tutorial
  [x] Informational content
  [ ] Other (describe)

- Which blockchain protocol is this about?: Any

- Description (two or three phrases describing what is it about):

This article aims to provide a comprehensive introduction to decentralized exchanges (DEXs) for readers who may be new to the concept. The article will explain the basics of DEXs, including how they differ from centralized exchanges and the benefits they offer. It will also delve into the technical details of how DEXs work, including how they facilitate peer-to-peer trading without the need for a central authority. In addition, the article will provide information on some popular DEX platforms that readers can consider. Overall, the article aims to give readers a solid foundation in DEXs and provide the necessary knowledge and resources to how to get started.

**Comment by Genesis3800** [comment]
Hey @TheGhoulRe ,
Thank you for your proposal to the developer hub.
Apologies for being so late to reply. 
Unfortunately, we are not looking to add informational content along these lines to our blog right now.
Feel free to propose more issues.
