### ISSUE TITLE
[PROPOSAL] Basic Flashbots tutorial

### ISSUE THREAD

**Issue by eserilev** [chainstack/developer-hub-content#5]
- Content is:
  [x] Coding tutorial
  [ ] Informational content
  [ ] Other (describe)

- Description (two or three phrases describing what is it about):
A basic tutorial on how and why to use flashbots 
- Have you published articles in a blog before? If so, please include some links below 👇
No

**Comment by uF4No** [comment]
hey @eserilev thanks for creating a proposal. We really like the idea.
Please [join the developer-hub channel in our Discord](https://discord.gg/Cymtg2f7pX) so we can talk in more detail about it and help you get it published 🤙
