### ISSUE TITLE
[A Detailed Guide to Understanding Account Abstraction in Web3 - Technical Content PROPOSAL]

### ISSUE THREAD

**Issue by johnfawole** [chainstack/developer-hub-content#52]
- Content is:
  [ ] Informational content

- Which blockchain protocol is this about? Ethereum

- Description (two or three phrases describing what is it about)
The main point of the article is to explain what account abstraction is all about, why it is necessary, and the various efforts to achieve it so far.

- Have you published articles in a blog before? If so, please include some links below 👇
- https://www.quicknode.com/guides/smart-contract-development/a-broad-overview-of-reentrancy-attacks-in-solidity-contracts 
***
# Content Outline

### Why is account abstraction important?

- user experience
- security
- upgradeability
- gasless transactions
- batch calling
- removal of ETH as the benchmark
- accommodation of other signature schemes
- one-wallet-for-all

Analyzing the EIPs on Account Abstraction So Far

- EIP 86
- EIP 1014
- EIP 2938
- EIP 3074
- EIP4337
### What are the L2 solutions working on account abstraction?

- StarkNet
- zkSync
- Optimism

### Are there currently some SDKs for account abstraction?

- Biconomy SDK
- Etherspot SDK

### Top 5 Wallets that are Supporting Account Abstraction

- Candide
- Argent
- Soul
- Unipass
- Openfort

**Comment by johnfawole** [comment]
@Genesis3800

**Comment by Genesis3800** [comment]
Hey @johnfawole ,
Thank you for your proposal. 
We really liked your mappings article, and are working towards pushing it to prod.

Unfortunately, we are not looking to add content along this line to our blog right now. 
Please feel free to go ahead and propose new topics.

**Comment by johnfawole** [comment]
Alright, thanks for your response.

I will draft and propose a new topic next week.

Do enjoy the rest of your weekend.
