### ISSUE TITLE
[PROPOSAL] Comparing Ethereum and web3: Understanding the Differences and Similarities

### ISSUE THREAD

**Issue by LucidRay** [chainstack/developer-hub-content#53]
- Content is:
  [ ] Coding tutorial
  [x] Informational content
  [ ] Other (describe)

- Which blockchain protocol is this about?:
Ethereum
- Description (two or three phrases describing what is it about):
This article helps the readers distinguish between the Web3js and the EthersJS module. In this article the readers will be given a clear understanding of the concepts that the two modules entail and they'll be able to understand why the both of them even exists.

- Have you published articles in a blog before? If so, please include some links below 👇
Yes,
https://www.section.io/engineering-education/getting-started-with-ray-tracing-algorithm-in-machine-learning/
https://www.section.io/engineering-education/recovering-wifi-passwords-from-operating-systems/

**Comment by Genesis3800** [comment]
Hey @LucidRay 
Thank you for your proposal to the developer hub.

Unfortunately, we are not looking to add informational content along these lines to our blog right now.
Feel free to propose more issues.
