### ISSUE TITLE
A Step-by-step Guide to Building a Robust Lending and Borrowing Protocol on the Ethereum Blockchain

### ISSUE THREAD

**Issue by johnfawole** [chainstack/developer-hub-content#57]
- Content is:
  [ ] Coding tutorial

- Which blockchain protocol is this about? Ethereum

- Description (two or three phrases describing what is it about):
- The focus of this tutorial is to build an over-collateralized lending and borrowing protocol. With this knowledge, you would also build an under-collateralized lending and borrowing protocol.

- Have you published articles in a blog before? If so, please include some links below 👇

### Outline

- Introduction
- What do lending and borrowing mean in crypto?
- Prerequisites
- Writing the Contract from Scratch
- Testing  with Foundry using the Chainstack RPC
- Conclusion

@Genesis3800 kindly check out my new content proposal. Thanks.

**Comment by Genesis3800** [comment]
Hey @johnfawole ,
Thank you for your proposal to the developer hub.

Unfortunately, we are not looking to add informational content to our blog right now.
Feel free to propose more issues.

To add more on that John, we look forward to adding more content to our blogs on new web3-specific protocols. We are looking for blogs that contain original code, and belong to a larger ecosystem, for example, Chainlink and The Graph. Try to think of something creative you can build using 1 or more web3 protocols. This way your proposal will have a higher chance of being accepted.
