### ISSUE TITLE
[PROPOSAL]

### ISSUE THREAD

**Issue by anshuman-dev** [chainstack/developer-hub-content#59]
- Content is:
Informational Content

- Which blockchain protocol is this about?:
It is about Ethereum, Polygon and Solana

- Description (two or three phrases describing what is it about):
Topic: Play and Earn!

I will be writing about P&E. With the first paragraph giving a lite introduction and the following paragraph focusing on definitions and meaning of P&E in Crypto industry. Following the introductions, I will introduce P2E and the difference between P2E and P&E. The article will then be followed by little insights on how psychology works in the P2E model and then we will dive into games and blockchain environments having huge and potential tractions of people following for playing these P&E games. Finally we will be concluding with a suitable conclusion.

- Have you published articles in a blog before? If so, please include some links below 👇
Yes, but this article is on Application Security:
https://about.gitlab.com/blog/2021/09/08/write-vulnerability-detection-rules/

**Comment by Genesis3800** [comment]
Hey @anshuman-dev ,
Thank you for adding your proposal to the developer hub.

Unfortunately, we are not looking to add informational content along these lines to our blog right now.
Please feel free to propose more issues.
