### ISSUE TITLE
[PROPOSAL] Crypto Tokens: ERC20, ERC721, and ERC1155

### ISSUE THREAD

**Issue by dpkreativ** [chainstack/developer-hub-content#6]
- Content is:
  [ ] Coding tutorial
  [x] Informational content
  [ ] Other (describe)

- Which blockchain protocol is this about?: 
Ethereum

- Description (two or three phrases describing what is it about):
Tokens are often a quicker way to leverage the existing standards of a successful and popular blockchain while building digital assets.
ERCs (Ethereum Request for Comments) and EIPs (Ethereum Improvement Proposals) help standardize the creation process, enabling more accessible interactions between token ecosystems.
This article discusses ERC-20 and ERC-721, highlighting their use-cases, similarities, and differences.

- Have you published articles on a blog before? If so, please include some links below 👇
[Infinite Scroll Image Cards in GatsbyJS ](https://mediajams.dev/post/infinite-scroll-image-cards-in-gatsbyjs)
[Handle Quick AI Text Detection in Images in NextJS](https://mediajams.dev/post/handle-quick-ai-text-detection-in-images-in-nextjs)
[The Ultimate Guide to React `useReducer` Hook (with examples)](https://www.memberstack.com/blog/react-usereducer)

### Proposed Outline:
- Introduction (*What are tokens? Why are they essential in Blockchain development?*)
- ERC-20 Tokens (*What are ERC-20 tokens? A short description, history, and use-cases*)
- ERC-721 Tokens (*What are ERC-721 tokens? A short description, history, and use-cases*)
- Comparing ERC-20 and ERC-721 Tokens (*List some comparisons between both tokens, highlighting similarities and differences*)
- Conclusion (*Summarize the article and draw conclusions*)
- Resources (*Helpful resources to understand ERC-20 and ERC-721 tokens*)

**Comment by uF4No** [comment]
hey @dpkreativ we like the idea but we think ERC20 and ERC721 are not enough nowadays. 

Would you be able to include [ERC1155](https://docs.openzeppelin.com/contracts/3.x/erc1155) and also expand on the different extensions of 721 like [ERC721A](https://www.erc721a.org/) and [ERC721Enumerable](https://docs.openzeppelin.com/contracts/4.x/api/token/erc721#IERC721Enumerable)?

**Comment by dpkreativ** [comment]
Hi @uF4No! 
Yes, I can include these suggested tokens in the article.

Here's my suggested update to the article's title: **Crypto Tokens: ERC-20, ERC-721, and ERC-1155**

### Proposed Outline:
- Introduction (*What are tokens? Why are they essential in Blockchain development?*)
- ERC-20 Tokens (*A short description of its features and use-cases*)
- ERC-721 Tokens (*A short description of its features and use-cases*)
- ERC-721Enumerable Tokens (*A short description of its features and use-cases*)
- ERC-721A Tokens (*A short description of its features and use-cases*)
- ERC-1155 Tokens (*A short description of its features and use-cases*)

- Conclusion (*Summarize the article and draw conclusions*)
- Resources (*Helpful resources to understand these tokens*)

**Comment by uF4No** [comment]
Can you also include some of the main methods in each? For example, `transfer`, `approve`, `totalSupply` and `balanceOf` for ERC20 and `mint`, `ownerOf`, `approve`, `transferFrom` for ERC721. That'd help people understand how to interact with these contracts

**Comment by dpkreativ** [comment]
Yes, @uF4No 
I will include the main methods in each of their short descriptions.

**Comment by dpkreativ** [comment]
Awesome!
