### ISSUE TITLE
[PROPOSAL]

### ISSUE THREAD

**Issue by y2danny** [chainstack/developer-hub-content#60]
# Solidity tutorial:  How to write and read View vs Pure Functions.
  [ ] Coding tutorial
  [ ] Informational content
 

- Ethereum and any EVM chain

- A tutorial on understanding functions in solidity and practical guide on how to use them to write smart contracts

- Yes, 👇

https://thenavigator.hashnode.dev/how-to-scaffold-and-deploy-a-smart-contract-to-the-ethereum-network

https://thenavigator.hashnode.dev/

https://medium.com/@danielanthonysworld/dialect-deep-dive-the-birth-of-a-smart-wallet-9b0c2fe1067a

https://medium.com/@danielanthonysworld

**Comment by Genesis3800** [comment]
Hey @y2danny  ,
Thank you for adding your proposal to the developer hub.

Unfortunately, we are not looking to add informational content along these lines to our blog right now.
Please feel free to propose more issues.
