### ISSUE TITLE
[PROPOSAL] Developing a Full NFT Collection using hardhat and Next.js

### ISSUE THREAD

**Issue by Christianaojo** [chainstack/developer-hub-content#63]
- Content is:
  [ ] Coding tutorial on developing a full NFT collection using hardhat and Next.js

- Which blockchain protocol is this about?: Ethereum 

- Description (two or three phrases describing what it is about):
In this article, we will provide a step-by-step guide to developing a full NFT collection using Hardhat and Next.js. Hardhat is a development environment for Ethereum-based projects, while Next.js is a popular React-based framework for building fast and efficient web applications. By following this guide, readers will gain hands-on experience in creating NFTs, managing collections, and deploying NFT projects to the web. Whether you're a seasoned developer or just starting out, this article will provide valuable insights into the world of NFT development.

- Have you published articles in a blog before? If so, please include some links below 👇
[https://dev.to/techiechristie/getting-started-with-blockchain-development-a-step-by-step-guide-to-deploying-your-first-dapp-58h0](Getting-started-with-blockchain-development-a-step-by-step-guide-to-deploying-your-first-dapp)

[link 2](https://dev.to/techiechristie/utilizing-the-benefits-of-smart-contract-security-auditing-23dk)

**Comment by Genesis3800** [comment]
Hey @Christianaojo  ,
Thank you for adding your proposal to the developer hub.

Unfortunately, we are not looking to add coding content along these lines to our blog right now.
Please feel free to propose more issues.
