### ISSUE TITLE
[PROPOSAL] The Role of Sharding in Scalability Solutions for Public Blockchains

### ISSUE THREAD

**Issue by Christianaojo** [chainstack/developer-hub-content#64]
- The content is:
  [ ] Coding tutorial
  [x] Informational content
  [ ] Other (describe)

- Which blockchain protocol is this about?: Public Blockchain

- Description (two or three phrases describing what it is about):
A comprehensive overview of the role of sharding in scalability solutions for public blockchains, and help readers understand why this technology is an important area of development for the future of blockchain technology

- Have you published articles in a blog before? If so, please include some links below 👇
 [Article 1](https://dev.to/techiechristie/utilizing-the-benefits-of-smart-contract-security-auditing-23dk)
 [Article 2](https://github.com/chainstack/developer-hub-content/issues/Getting-started-with-blockchain-development-a-step-by-step-guide-to-deploying-your-first-dapp)

**Comment by Genesis3800** [comment]
Hey @Christianaojo ,
Thank you for adding your proposal to the developer hub.

Unfortunately, we are not looking to add coding content along these lines to our blog right now.
Please feel free to propose more issues.

As of now, we are primarily looking to add coding content to our blog that focusses on new protocols and technologies. You can check out currently accepted proposals for more information.
