### ISSUE TITLE
[PROPOSAL]

### ISSUE THREAD

**Issue by y2danny** [chainstack/developer-hub-content#68]
- Content is:
  [ ] Informational content

- Ethereum

- Topic: How are defi protocols giving you interest rates the banks can not?
   An in-depth look into the mechanism, economics and engineering which defi protocols uses to achieve high yields our banks 
   possibly cannot.

- Yes, 👇
   [blog](https://thenavigator.hashnode.dev/)

**Comment by Genesis3800** [comment]
Hey @y2danny  ,
Thank you for adding your proposal to the developer hub.

Unfortunately, we are not looking to add coding content along these lines to our blog right now.
Please feel free to propose more issues.

Please check out already accepted issues and merged proposals for a better idea.
As of now, we are looking for content that focusses on relatively recent web3 tooling. For example, foundry, zk EVMs, etc.....
We prefer articles with original code along these lines.
