### ISSUE TITLE
[PROPOSAL] How to mint and transfer Ethereum NFTs programmatically

### ISSUE THREAD

**Issue by tster** [chainstack/developer-hub-content#7]
- Content is:
  [x ] Coding tutorial
  [ ] Informational content
  [ ] Other (describe)

- Which blockchain protocol is this about?: Ethereum

- Description (two or three phrases describing what is it about): This article will show readers how to mint and transfer Ethereum NFTs programmatically. It will include TypeScript code samples using the ethers.js library to interact with the Ethereum network. It will also demonstrate how to generate the appropriate hex data to interact with a contract's write function.

- Have you published articles in a blog before? If so, please include some links below 👇
https://nordicapis.com/author/thomas_bush/

**Comment by uF4No** [comment]
Hi @tster 
Could this be a tutorial on how to create an NFT collection and how to mint and distribute the NFTs?
Do you plan to include a basic frontend as well or the mint/distribution will be a backend job?

**Comment by tster** [comment]
Hi @uF4No, for this proposal, I was just going to focus on programmatically minting and transferring NFTs from existing collections using a library like ethers.js, without a frontend. By extension, this guide would teach readers the basics of interacting with _any_ Ethereum smart contract programmatically (by demonstrating how to call on-chain functions using ethers).

Ideally, I would cover the creation of new NFT collections (and smart contracts) in [proposal #10](https://github.com/chainstack/developer-hub-content/issues/10), since that is a different audience and skillset.

The guides would overlap thematically (because they'd both cover NFTs), but again, they would target very different users and skills.

**Comment by uF4No** [comment]
@tster As mentioned in #10, I think we should merge the two proposals, close that one and keep this one open. The article should focus on how to create an NFT collection, mint, and transfer them.

**Comment by tster** [comment]
> @tster As mentioned in #10, I think we should merge the two proposals, close that one and keep this one open. The article should focus on how to create an NFT collection, mint, and transfer them.

That works for me!

**Comment by uF4No** [comment]
Cool. I suggest we move the conversation to our Discord. Feel free to send a message in the developer-hub channel with the table of contents so we can get things rolling 🤙
