### ISSUE TITLE
[PROPOSAL]Introduction to Blockchain-Based Data Sources

### ISSUE THREAD

**Issue by oyedeletemitope** [chainstack/developer-hub-content#70]
- Content is:
  [ ] Coding tutorial
  [x] Informational content
  [ ] Other (describe)

- Which blockchain protocol is this about?:

- Description (two or three phrases describing what is it about):

 The decentralized and immutable nature of blockchain has made it an attractive solution for various industries, including finance, supply chain management, and healthcare. However, blockchain technology alone is not enough to ensure the accuracy and reliability of the data stored on the blockchain. This is where blockchain-based data sources come in.

In this article, I'll be talking about what blockchain-based data sources are all about.

**Outline**

- Introduction
- Definition of blockchain-based data sources
- types of blockchain-based data sources 
- benefits of  blockchain-based data sources
- use cases of blockchain-based data sources
- challenges of blockchain-based data sources
- future development in blockchain-based data sources
- conclusion

- Have you published articles in a blog before? If so, please include some links below 👇

**Comment by Genesis3800** [comment]
Hey @oyedeletemitope  ,
Thank you for adding your proposal to the developer hub.

Unfortunately, we are not looking to add informational content along these lines to our blog right now.
Please feel free to propose more issues.
