### ISSUE TITLE
[PROPOSAL] Auditing Decentralized Applications for Security Vulnerabilities.

### ISSUE THREAD

**Issue by Christianaojo** [chainstack/developer-hub-content#72]
- Content is:
  [x] Coding tutorial
  [x] Informational content
  [ ] Other (describe)

- Which blockchain protocol is this about?:
Ethereum
- Description (two or three phrases describing what is it about):
1.  Importance of security in dApps
2.  Types of Security Vulnerabilities in dApps
3.  Approaches to Auditing dApps for Security Vulnerabilities
4.  Future of dApp security and auditing.
- Have you published articles in a blog before? If so, please include some links below 👇
 [article 1](https://dev.to/techiechristie/utilizing-the-benefits-of-smart-contract-security-auditing-23dk)
[article 2](https://dev.to/techiechristie/getting-started-with-blockchain-development-a-step-by-step-guide-to-deploying-your-first-dapp-58h0)

**Comment by Genesis3800** [comment]
Hey @Christianaojo  ,
Thank you for adding your proposal to the developer hub.

Unfortunately, we are not looking to add coding content along these lines to our blog right now.
Please feel free to propose more issues.

We could have accepted this proposal @Christianaojo , but a similar proposal was unfortunately approved recently, so it does not make sense for us to have another blog on the same topic.
