### ISSUE TITLE
[PROPOSAL] How to Create a Multi-Signature Wallet on StarkNet

### ISSUE THREAD

**Issue by Christianaojo** [chainstack/developer-hub-content#73]
- Content is:
  [x] Coding tutorial
  [ ] Informational content
  [ ] Other (describe)

- Which blockchain protocol is this about?:
StarkNet

- Description (two or three phrases describing what is it about):
Creating a Multi-Signature Wallet on StarkNet
Setting up the development environment
Writing the smart contract code
Compiling and deploying the smart contract
Interacting with the deployed contract
Testing and Debugging the Multi-Signature Wallet

- Have you published articles in a blog before? If so, please include some links below 👇
[Article 1](https://dev.to/techiechristie/utilizing-the-benefits-of-smart-contract-security-auditing-23dk)
[Article 2](https://dev.to/techiechristie/getting-started-with-blockchain-development-a-step-by-step-guide-to-deploying-your-first-dapp-58h0)

**Comment by Genesis3800** [comment]
Hey @Christianaojo ,
Thank you for adding your proposal to the developer hub.

Unfortunately, we are not looking to add coding content along these lines to our blog right now.
Please feel free to propose more issues.

Hey @Christianaojo , I see that you have proposed a few issues with us already. Let me give you a general brief on what we are looking for.

We are, at the moment, giving a strong preference to blogs that contain original code, so coding articles.
Also, we already have a bunch of stuff covering tools like Hardhat and Foundry, along with protocols like Starknet and Polygon.

As of now, we are mainly looking for blogs on topics that haven't been yet covered extensively.
