### ISSUE TITLE
Building & Automating your NFT Auction Smart Contract with Chainlink

### ISSUE THREAD

**Issue by johnfawole** [chainstack/developer-hub-content#74]
- Content is:
  [ ] Coding tutorial
 

- Which blockchain protocol is this about? Ethereum

- Description (two or three phrases describing what is it about):  Chainlink Keepers is a great automation feature that developers can use to automate functions in their contract. This tutorial aims to give real-time technical guidance to developers so they can use this product with the Chainstack API.

- Have you published articles in a blog before? If so, please include some links below 👇
- https://docs.celo.org/blog/tutorials/create-a-crowdfunding-smart-contract-on-celo-using-hardhat

***
Outline

- Introduction
- Smart Contract Automation Problem
- Chainlink Keepers
- Building a simple NFT Auction smart contract
- Deploying your contract with Alchemy
- Automating your contract
- Automation Verification
- Conclusion

***
Please, check this coding tutorial @Genesis3800.

**Comment by Genesis3800** [comment]
Hey @johnfawole ,
Thank you for adding your proposal to the developer hub.

Unfortunately, we are not looking to add coding content along these lines to our blog right now.
Please feel free to propose more issues.
