### ISSUE TITLE
[PROPOSAL]

### ISSUE THREAD

**Issue by MAKE-star** [chainstack/developer-hub-content#75]
- Content is:Coding/Informational 
  [ ] Coding tutorial
  [ ] Informational content
  [ ] Other (describe)

- Which blockchain protocol is this about?:Binance Smart Chain

- Description (two or three phrases describing what is it about):How to create a Car Hiring App using Solidity 

- Have you published articles in a blog before? If so, please include some links below 👇

https://t.co/NvoX9kc7oP

**Comment by Genesis3800** [comment]
Hey @MAKE-star  ,
Thank you for adding your proposal to the developer hub.

Unfortunately, we are not looking to add informational content along these lines to our blog right now.
Please feel free to propose more issues.

**Comment by MAKE-star** [comment]
Thanks for your reply
I will love if you could suggest areas you might want proposals on

I will await your response.
Thanks
