### ISSUE TITLE
[PROPOSAL] Integrating IPFS with Ethereum Blockchain

### ISSUE THREAD

**Issue by theifedayo** [chainstack/developer-hub-content#76]
- Content is:
  [ ] Coding tutorial
  [ ] Informational content
  [ ] Other (describe)

- Which blockchain protocol is this about?: 
     Ethereum

- Description (two or three phrases describing what is it about):
    * Introduction to IPFS and Ethereum: Provide a brief overview of IPFS and Ethereum, and explain why integrating them can be beneficial for decentralized applications (dApps).
    
    * Setting up IPFS and Ethereum: Provide step-by-step instructions on how to set up an IPFS node and an Ethereum node on your local machine.
    
    * Uploading Files to IPFS: Show how to upload a file to IPFS using the IPFS command-line interface (CLI) or the web-based IPFS desktop app.
    
    * Integrating IPFS with Ethereum: Demonstrate how to use IPFS to store files on the Ethereum blockchain using smart contracts. Write a simple smart contract that allows users to upload and download files from IPFS.
    
    * Testing the Integration: Installing the smart contract on the Ethereum network and interacting with it through a web3-enabled browser or the Remix IDE will allow you to test the integration. Demonstrate the use of the smart contract to upload and download files via IPFS.
    
    * Conclusion:  Recap on why integrating IPFS with Ethereum Blockchain can be beneficial for dApps, Summary of the hands-on lessons, call to actions for readers to integrate IPFS with blockchain.

- Have you published articles in a blog before? If so, please include some links below 👇
    * https://medium.com/@theifedayo/building-more-reliable-applications-with-temporal-7e7aa8868f40
    * https://dev.to/ifedayo/writing-your-first-tests-for-nodejs-apps-h5p
    * https://dev.to/ifedayo/reading-files-as-environment-variables-in-nodejs-57g3

**Comment by Genesis3800** [comment]
Hey @theifedayo  ,
Thank you for adding your proposal to the developer hub.

Unfortunately, we are not looking to add coding content along these lines to our blog right now.
Please feel free to propose more issues.
