### ISSUE TITLE
[PROPOSAL]

### ISSUE THREAD

**Issue by codekyng** [chainstack/developer-hub-content#80]
- Content is:
  [ ] Coding tutorial

- Which blockchain protocol is this about?:
- Layer 2 Blockchains

- Description (two or three phrases describing what is it about):
- Blockchain technology has revolutionized the way we conduct transactions and transfer value, but with its increasing popularity, scalability has become a major concern. To address this issue, researchers and developers have come up with a solution known as Layer 2 blockchains. In this article, we will explore the different types of Layer 2 blockchains, their benefits, and drawbacks.

- Have you published articles in a blog before? If so, please include some links below 👇
- Yes.
- https://codekyng.hashnode.dev/how-to-build-an-ethereum-crud-application-with-solidity
- https://codekyng.hashnode.dev/how-to-test-your-smart-contract-with-truffle

**Comment by Genesis3800** [comment]
Hey @codekyng  ,
Thank you for adding your proposal to the developer hub.

Unfortunately, we are not looking to add informationL content along these lines to our blog right now.
Please feel free to propose more issues.
