### ISSUE TITLE
[PROPOSAL]

### ISSUE THREAD

**Issue by okoba** [chainstack/developer-hub-content#81]
- Content is:
  [x] Securing Wallets and Staking on Ethereum Blockchain i.e. Protecting Your Assets with Code.
  [x] Informational content.
 To educate future readers on the key concepts related to wallets and staking on Ethereum blockchain and give them the necessary steps to ensure the security of their assets.

  [ ] Other (describe)

- Which blockchain protocol is this about?
- Ethereum.
 - Description (two or three phrases describing what is it about):
- Introduction to Ethereum blockchain
- Code security for wallet and staking on Ethereum Blockchain
- Security of wallets on Ethereum blockchain

- Have you published articles in a blog before? If so, please include some links below 👇
* [link 1] (https://medium.com/coinsbench/solidity-for-beginners-understanding-the-features-of-solidity-53adc9a19d1e) 
* [Link 2] (https://medium.com/@okobagloria/erc-20-token-development-understanding-the-key-features-of-erc-20-standards-82c6f6a10ed7)

**Comment by Genesis3800** [comment]
Hey @okoba ,
Thank you for adding your proposal to the developer hub.

Unfortunately, we are not looking to add coding content along these lines to our blog right now.
Please feel free to propose more issues.

**Comment by okoba** [comment]
Thanks for the clarification.
Will like to know what content is appropriate at this time though.
