### ISSUE TITLE
[PROPOSAL] "The Scalability Trilemma and How Layer 2 Chains Are Addressing It"

### ISSUE THREAD

**Issue by Jimrealf** [chainstack/developer-hub-content#82]
- Content is:
  [ ] Coding tutorial
  [ X] Informational content
  [ ] Other (describe)

- Which blockchain protocol is this about?: 
Ethereum

- Description (two or three phrases describing what is it about):
This article will shed light on the scalability trilemma as regards the Ethereum Network.
Blockchains, you see, has never been able to score a perfect 10/10 as far as we know, in terms of Scalability, decentralization and security. 
This article will discuss the challenges faced by the Ethereum Network in tackling all three of these facets simultaneously, and how layer 2 solutions come into the picture to make the chain more scalable, decentralized and secure without trading one for the other.

- Have you published articles in a blog before? If so, please include some links below 👇
https://voiceofcrypto.online/author/jimrealf/
https://voiceofcrypto.online/ethereum-eth-price-prediction-january-2023/
https://voiceofcrypto.online/here-are-three-of-the-most-notable-crypto-predictions-by-big-short-michael-burry/
https://voiceofcrypto.online/top-5-altcoins-on-the-verge-of-breakout-2/
https://voiceofcrypto.online/kucoin-and-crypto-com-tokens-plunge-after-ftx-fall/
https://voiceofcrypto.online/australian-watchdog-sues-bps-for-misrepresenting-qoin-token/

**Comment by Genesis3800** [comment]
Hey @Jimrealf  ,
Thank you for adding your proposal to the developer hub.

Unfortunately, we are not looking to add informational content along these lines to our blog right now.
Please feel free to propose more issues.
