### ISSUE TITLE
[PROPOSAL] Comparison between Daml and Solidity

### ISSUE THREAD

**Issue by JudyNduati** [chainstack/developer-hub-content#93]
- Content is:
  [ ] Coding tutorial
  [x ] Informational content
  [ ] Other (describe)

- Which blockchain protocol is this about?: Daml and Solidity

- Description (two or three phrases describing what is it about):
Daml is an open-source platform smart contracts language for creating composable business workflows and applications. It takes that massive fragmented system and gives you the best tangible representation of your business process. On the other hand, Solidity is a high-level language for writing smart contracts.
This article will give an in-depth understanding of Daml and Solidity. You will understand how they work and the role they play explained thoroughly. Also, you will get to know how Daml is used for Blockchain for business and give business use case examples to have a clear understanding.

- Have you published articles in a blog before? If so, please include some links below 👇
https://www.section.io/engineering-education/overview-of-web-3-0/
https://www.section.io/engineering-education/what-it-takes-to-be-a-devops-engineer/
https://mattermost.com/blog/best-search-packages-for-javascript/
https://signoz.io/blog/elasticsearch-vs-mongodb/

**Comment by Genesis3800** [comment]
Hey @JudyNduati ,
Thank you for adding your proposal to the developer hub.

Unfortunately, we are not looking to add informational content along these lines to our blog right now.
Please feel free to propose more issues.
